[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "target-feature=+crt-static"]

[target.aarch64-unknown-linux-gnu]
rustflags = ["-C", "target-feature=+crt-static"]

[target.armv7-unknown-linux-gnuabihf]
rustflags = ["-C", "target-feature=+crt-static"]
